version: "3.8"

services:
  postgres:
    image: postgres:17.3-alpine3.21
    container_name: postgres-trusodrom
    ports:
      - "5440:5432"
    volumes:
      - .:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "GGzS6AJHsArdm_tSn_H0"
      POSTGRES_DB: "trusodrom-db"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8"
      PGDATA: "/var/lib/postgresql/data/pgdata"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d trusodrom-db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - trusodrom-network

  redis:
    image: redis:alpine3.21
    container_name: redis-trusodrom
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - './data/redis:/data'
    networks:
      - trusodrom-network

  rabbitMQ:
    image: rabbitmq:management-alpine
    container_name: rabbitMQ-trusodrom
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - '5672:5672'
      - '15672:15672'
      - '15692:15692'
    restart: unless-stopped
    volumes:
      - './data/rabbitmq:/var/lib/rabbitmq'
    networks:
      - trusodrom-network
    depends_on:
      - postgres
      - redis

networks:
  trusodrom-network:
    driver: bridge